# Use an official Python runtime as a base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install Python dependencies
RUN pip install -r requirements.txt

# Copy the Flask application code into the container
COPY . .

# Expose the port that Flask will run on (usually 5000)
EXPOSE 5000

# Define the command to start the Flask application
CMD ["python", "app.py"]
